ethersphere/bee-dashboard

src/components/CodeBlockTabs.tsx, src/components/EthereumAddress.tsx, src/components/EthereumAddressCard.tsx, src/components/NavBar.tsx, src/components/SideBar.tsx, src/components/TroubleshootConnectionCard.tsx, src/hooks/apiHooks.tsx, src/pages/accounting/AccountCard.tsx, src/pages/accounting/index.tsx, src/pages/status/NodeSetupWorkflow.tsx, src/pages/status/SetupSteps/ChequebookDeployFund.tsx, src/pages/status/SetupSteps/EthereumConnectionCheck.tsx, src/pages/status/SetupSteps/NodeConnectionCheck.tsx, src/pages/status/SetupSteps/PeerConnection.tsx, src/pages/status/StatusCard.tsx
Typography, by default, uses <p> as it's underlying component. When used
to embed other components it resulted in a DOM errors like: "<p> cannot appear
as descendant of <p>"... and more.
fix: Linting
=> fix: Setting explicit Typography components to fix invalid DOM

.env.production
Adding the necessary environment variables to mirror [.env.development](https://github.com/ethersphere/bee-dashboard/blob/master/.env.development) to fix broken links to the discord server and etherscan
=> fix: broken links /add prod env variables

.gitattributes
Addresses issue with windows builds. Some repo clones on windows automatically convert line endings of files to `CRLF` if their git settings are not configured for autocrlf [See link](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings) This causes issues with prettier on build ["endOfLine": "lf"](https://github.com/ethersphere/bee-dashboard/blob/master/.prettierrc#L10) and will result in the below error of `delete cr`. 
Alternatively, in the `.prettierrc` file **endOfLine** can be changed to "auto" but I think this is cleaner. [See "endOfLine"](https://github.com/ethersphere/bee-dashboard/blob/master/.prettierrc#L10)
=> fix: add git attributes

src/components/AlertVersion.tsx
Before the fix:
After the fix:
=> fix: don't display version alert when unable to retrieve version from bee node

src/components/CashoutModal.tsx, src/hooks/accounting.ts, src/utils/index.ts
Reworked `Promise.all` to `Promise.allSettled`
Added utility fn to create retriable Promise
Before:
After:
=> feat: add retry to accounting

src/pages/status/NodeSetupWorkflow.tsx
This button is no longer needed as the page refreshes itself automatically
=> chore: remove refresh button on node setup

package.json
The types and the assets are not available in the npmjs package of the library at this moment.
This PR will fix that for the next build and release.
Thanks @AuHau for the tip!
=> fix: package.json files

src/providers/Settings.tsx
I was trying to figure out why the urls don't propagate well to `bee-dashboard` and started with reducing the moving parts. This refactor is just that, it reduces moving parts :).
=> refactor: settings to use less useEffects (and therefore less re-renders)

src/pages/files/DownloadActionBar.tsx
There is no existing issue for this, just a minor visual glitch I found
=> fix: clean up spinner and disabled state on download page

src/components/SwarmSelect.tsx, src/components/SwarmTextInput.tsx
Removes border radius, padding, some gray backgrounds, and cleans up floating label being in awkward positions
=> style: make select and text input style consistent

src/pages/info/index.tsx, src/pages/status/SetupSteps/ChequebookDeployFund.tsx, src/pages/status/SetupSteps/DebugConnectionCheck.tsx, src/pages/status/SetupSteps/EthereumConnectionCheck.tsx, src/pages/status/SetupSteps/NodeConnectionCheck.tsx, src/pages/status/SetupSteps/PeerConnection.tsx, src/pages/status/SetupSteps/VersionCheck.tsx, src/providers/Bee.tsx
fixes #309
resolves #307
I've decided to implement the disabling/enabling of the sidebar menu items in a different PR (e.g. chequebook should not be available in ultra-light mode)
=> feat: detect bee mode and enable/disable status checks accordingly

src/components/ExpandableListItemInput.tsx, src/hooks/apiHooks.tsx, src/pages/settings/index.tsx, src/providers/Settings.tsx, src/utils/net.ts
This is very much work in progress but would love to start the discussion. You can test this this by starting `bee-dashboard` with `export REACT_APP_CONFIG_URL=http://localhost:3000/config` and running `bee-desktop` with this branch https://github.com/ethersphere/bee-desktop/pull/25
TODO:
=> feat: add bee-desktop settings capabilities

src/pages/stamps/PostageStampCreation.tsx
resolves #326
I've tested this and it works fine with any UTF-8 string on bee dev and bee-factory (even put it some evil czech characters :) )
=> fix: remove restrictions on postage stamp label

src/pages/stamps/PostageStampCreation.tsx, src/utils/index.ts
resolves #321 
This is a very minimal implementation of the functionality. I would like to point out that the UX here is pretty bad as it does not tell the user what is happening (e.g. the stamp was bought waiting for it to be usable) and if for whatever reason the stamp is not usable until the `DEFAULT_STAMP_USABLE_TIMEOUT = 120_000` is reached, it will fail with error message. My suggestion would be to merge this PR but have a design session with David how to improve the UX. On mainnet purchasing the stamp will take 30-90 seconds and then waiting for it to be usable also takes up to 90 seconds.
=> feat: wait for postage stamp to be usable when bying it

src/providers/Bee.tsx
For some reason, the check always run twice. But this was the case before as well (and I will create an issue about it).
=> feat: refresh frequency changes if the bee is in error state

src/pages/account/chequebook/AccountChequebook.tsx, src/pages/account/wallet/AccountWallet.tsx
Instead of fully hiding the Account page when loading the balances, this will only place the spinner in place of the balances, so the navigation and other information (even in ultra light mode) remains visible and functional.
=> fix: display account wallet partially while loading

src/pages/files/UploadActionBar.tsx
=> fix: don't display buy new stamp button when already in process of buying one

src/pages/rpc/index.tsx
Added the medium blog post as a link instead of `getblock.io` after getting the feedback that people just copied it as is as an RPC endpoint.
=> feat: add upgrade guide link from medium

src/pages/gift-code/index.tsx
Ideally we would send these amounts with the request to the bee-desktop but lets not do that now.
=> fix: generate gift wallet is disabled if there is not enough funds

src/utils/bzz-abi.ts, src/utils/rpc.ts, src/utils/wallet.ts
So this is by no means perfect:
- It does not have any retry mechanism
- it does not correctly check on the UI if the balance is enough for both of the transfers.
But I think it is improvement over what is there right now.  I would like to do a complete refactor of this code later (we are creating providers all the time, I think we can better encapsulate things etc).
=> feat: transfer everything out of the gift wallet

src/pages/gift-code/index.tsx, src/pages/settings/index.tsx, src/pages/top-up/GiftCardFund.tsx, src/pages/top-up/GiftCardTopUpIndex.tsx, src/pages/top-up/Swap.tsx, src/pages/top-up/index.tsx, src/providers/Bee.tsx, src/providers/Settings.tsx, src/providers/TopUp.tsx, src/utils/net.ts
=> feat: make blockchain JSON RPC configurable from settings

src/pages/account/wallet/AccountWallet.tsx, src/routes.tsx
=> fix: disable swarm invitation outside of Swarm Desktop

src/pages/stamps/PostageStampCreation.tsx
Since we have a custom waiting mechanism (only wait for "exists", then let user continue the flow, and wait for "usable" before uploading) I think this is needed.
=> fix: set waitForUsable to false

.env.development, .env.production, README.md, src/App.tsx, src/index.tsx, src/pages/gift-code/index.tsx, src/pages/settings/index.tsx, src/pages/top-up/GiftCardFund.tsx, src/pages/top-up/GiftCardTopUpIndex.tsx, src/pages/top-up/Swap.tsx, src/pages/top-up/index.tsx, src/providers/Settings.tsx, src/providers/TopUp.tsx, src/providers/WalletBalance.tsx
This reverts the renaming of env. variables to set Bee (Debug) API and also reintroduce the `REACT_APP_DEFAULT_RPC_URL` variable.
=> fix: revert bee env. variable names and add default rpc var

src/hooks/apiHooks.tsx, src/pages/settings/index.tsx, src/providers/Settings.tsx, src/utils/desktop.ts
We can't set the RPC URL to the `swap-endpoint` Bee config value unless the Bee node is already in light mode as setting this config value, basically upgrades the node to light mode.
=> fix: rpc endpoint setting ultra-light mode logic

src/hooks/apiHooks.tsx, src/pages/status/SetupSteps/ChequebookDeployFund.tsx, src/pages/status/SetupSteps/DebugConnectionCheck.tsx, src/pages/status/SetupSteps/DesktopConnectionCheck.tsx, src/pages/status/SetupSteps/NodeConnectionCheck.tsx, src/pages/status/SetupSteps/PeerConnection.tsx, src/pages/status/index.tsx
- Desktop mode has a new Swarm Desktop Connection check (todo: check periodically instead of initially)
- Desktop mode no longer has the version check (it is different and is on the info page)
- Chequebook check and Peer Connectivity check are removed when connection to the debug API fails, previously it was stuck in green state
=> fix: change status page depending on desktop mode

package-lock.json, package.json, src/components/Card.tsx, src/pages/info/ChequebookInfoCard.tsx, src/pages/info/NodeInfoCard.tsx, src/pages/info/WalletInfoCard.tsx, src/pages/info/index.tsx, src/providers/Bee.tsx, src/utils/net.ts
This PR extracts the status cards on info/home page.
Add readiness to provider.
And implements a loading state when node is healthy but not ready.
Only one card is shown during that time period.
=> fix: add loading state to info page

src/components/ProgressBar.tsx, src/pages/files/AssetSyncing.tsx, src/pages/files/Share.tsx, src/pages/files/Upload.tsx
Additional helper text added. Currently, if the application is closed during a local node upload, the upload fails. This functionality should ideally work seamlessly, even if the process happens in the background. I believe it's better to address this issue in a separate pull request.
I monitor the syncing progress using the '/tags' endpoint. Once it reaches 70%, I begin utilizing one of the stewardship endpoints to enhance syncing resilience against potential issues with the syncing data.
related issues:
https://github.com/ethersphere/bee-dashboard/issues/605
https://github.com/ethersphere/swarm-desktop/issues/385
@ethersphere/solar-punk
=> feat: wait for upload sync
