src/pages/status/NodeSetupWorkflow.tsx
src/pages/status/SetupSteps/DebugConnectionCheck.tsx
src/pages/status/SetupSteps/NodeConnectionCheck.tsx

feat: split api status checks

---

src/hooks/apiHooks.tsx
src/pages/files/index.tsx
src/services/bee.tsx

Replaces the axios call for the Bee endpoint, fixes the interfaces for file upload and download.
The file download does not work well for me, but this PR does not really change it so I'll just create an issue about it as I think that part should anyways be refactored into more react way - see #39

refactor: use bee-js for health endpoint

---

package-lock.json
package.json
src/App.tsx
src/components/EthereumAddressCard.tsx

Removes code and functionality that is not implemented. See #28

refactor: remove unused code and packages

---

src/pages/files/index.tsx

resolves #59 , #28 
- error handling for file search and upload
- upload limited to 1 file
- file is download by opening new window to the bee node

fix: file download redirects to bee node, upload limited to 1 file

---

src/components/EthereumAddressCard.tsx
src/hooks/apiHooks.tsx
src/hooks/status.ts
src/pages/accounting/index.tsx
src/pages/status/NodeSetupWorkflow.tsx
src/pages/status/SetupSteps/ChequebookDeployFund.tsx
src/pages/status/SetupSteps/DebugConnectionCheck.tsx
src/pages/status/SetupSteps/EthereumConnectionCheck.tsx
src/pages/status/SetupSteps/NodeConnectionCheck.tsx
src/pages/status/SetupSteps/PeerConnection.tsx
src/pages/status/SetupSteps/VersionCheck.tsx
src/pages/status/StatusCard.tsx
src/pages/status/index.tsx
src/react-app-env.d.ts

Reviewed the wording and refactored to eliminate un-renderable states but also to make the node setup a bit cleaner. This can be even further simplified when we have a context provider (see #40 ) and we can even store state there.

feat: reviewed and simplified the node status check

---

src/pages/accounting/AccountCard.tsx

style: chequebook header in accounting page

---

src/components/ErrorBoundary.tsx
src/layout/Dashboard.tsx

feat: added error boundary for each page so errors don't crash the whole app

---

README.md
package-lock.json
package.json
serve.js

This setup this package to be (hopefully) released to NPM. It introduces `bee-dashboard` binary command that starts HTTP server and serve the `./build` folder.

feat: npm release support

---

.github/workflows/publish_npmjs.yaml

Tested on a fork https://github.com/vojtechsimetka/bee-dashboard/actions/runs/792915852
```
npm install -g @vojtechsimetka/bee-dashboard
bee-dashboard
```

ci: release to npmjs

---

package-lock.json
package.json
src/components/EthereumAddressCard.tsx
src/hooks/accounting.ts
src/hooks/apiHooks.tsx
src/hooks/status.ts
src/pages/files/index.tsx
src/pages/settings/index.tsx
src/pages/status/SetupSteps/ChequebookDeployFund.tsx
src/pages/status/StatusCard.tsx
src/services/bee.tsx

feat: update to bee v0.6.0

---

README.md
src/pages/status/SetupSteps/DebugConnectionCheck.tsx
src/pages/status/SetupSteps/NodeConnectionCheck.tsx

fix: troubleshooting on a mac and clearer CORS setup guide

---

package-lock.json
package.json
src/App.tsx
src/components/CashoutModal.tsx
src/components/ClipboardCopy.tsx
src/components/WDModal.tsx
src/pages/files/Upload.tsx
src/pages/stamps/CreatePostageStampModal.tsx

https://user-images.githubusercontent.com/7974813/120387155-d46e3580-c329-11eb-8415-e23ec49f5452.mov

feat: unified notification with notistack

---

package-lock.json
package.json
src/components/AlertVersion.tsx
src/components/CashoutModal.tsx
src/components/WDModal.tsx
src/hooks/status.ts
src/layout/Dashboard.tsx
src/pages/status/StatusCard.tsx
src/pages/status/index.tsx
src/react-app-env.d.ts
src/services/bee.tsx

https://user-images.githubusercontent.com/7974813/120489705-22ca1580-c3b8-11eb-8354-1448ec92a2d1.mov

feat: added tolerance to version check and warning if not exact to what we tested

---

src/pages/stamps/CreatePostageStampModal.tsx

fix: type error in the postage stamps form

---

src/pages/files/SelectStamp.tsx
src/pages/files/Upload.tsx
src/pages/stamps/StampsTable.tsx
src/providers/Stamps.tsx

feat: display postage batch usage percentage

---

src/pages/files/Upload.tsx

https://github.com/Yuvaleros/material-ui-dropzone/issues/9#issuecomment-460022810

fix: clear dropzone state after upload

---

README.md

fix: amend readme

---

.env.development
.env.production
src/components/CashoutModal.tsx
src/components/EthereumAddress.tsx
src/components/EthereumAddressCard.tsx
src/components/NavBar.tsx
src/pages/status/SetupSteps/ChequebookDeployFund.tsx
src/pages/status/SetupSteps/EthereumConnectionCheck.tsx

feat: updated troubleshooting instructions and links for mainnet

---

src/App.tsx
src/components/CodeBlockTabs.tsx
src/components/TabsContainer.tsx
src/providers/Platform.tsx

feat: synchronized platform tabs

---

src/pages/peers/PeerTable.tsx

fix: remove nested ternary operator and simplify ping peer functionality

---

package-lock.json
package.json

chore: update to latest bee version 1.1.0

---

src/components/SideBar.tsx
src/components/TopologyStats.tsx
src/components/TroubleshootConnectionCard.tsx
src/layout/Dashboard.tsx
src/pages/peers/PeerTable.tsx
src/pages/settings/index.tsx
src/theme.tsx

feat: troubleshooting component

---

package-lock.json
package.json
src/pages/files/Download.tsx
src/pages/files/Upload.tsx

chore(deps): update bee-js to 2.0.0

---

README.md
src/components/ExpandableListItemKey.tsx
src/providers/Bee.tsx

Usage:
`REACT_APP_DEV_MODE=1 npm start`

feat: add dev mode flag

---

src/utils/file.ts

fix: correct folder name when uploading multiple files or mix of files & directories

---

src/pages/files/Upload.tsx
src/utils/file.ts

This should probably be refactored, but it works.

fix: upload websites that are inside a folder

---

.github/workflows/check.yaml
package-lock.json
package.json

ci: enable depcheck

---

.github/workflows/check.yaml
.github/workflows/release_github.yaml

This PR consolidates secrets variables, we defined some org wide variables and from now on we will rotate and manage those variables more easily

replace REPO_GHA_PAT with GHA_PAT_BASIC

---

src/components/SideBarStatus.tsx
src/components/StatusIcon.tsx
src/pages/accounting/index.tsx
src/pages/feeds/index.tsx
src/pages/files/Upload.tsx
src/pages/info/index.tsx
src/pages/stamps/index.tsx
src/pages/status/SetupSteps/ChequebookDeployFund.tsx
src/pages/status/SetupSteps/DebugConnectionCheck.tsx
src/pages/status/SetupSteps/EthereumConnectionCheck.tsx
src/pages/status/SetupSteps/NodeConnectionCheck.tsx
src/pages/status/SetupSteps/PeerConnection.tsx
src/pages/status/SetupSteps/VersionCheck.tsx
src/providers/Bee.tsx
src/react-app-env.d.ts
src/types.ts

feat: optional status checks (e.g. connected peers > 0 or funded chequebook)

---

src/pages/stamps/PostageStampCreation.tsx

fix: show current postage stamp price per block

---

src/pages/stamps/PostageStamp.tsx
src/pages/stamps/StampsTable.tsx

feat: add aditional information to the stamps overview

---

src/pages/stamps/PostageStampCreation.tsx

fix: app crash caused by inputing non-number characters

---

src/constants.ts
src/pages/files/Download.tsx
src/utils/index.test.ts
src/utils/index.ts

feat: support for bzz.link cids when downloading files

---

src/pages/files/Upload.tsx
src/utils/file.ts

fix: nested directory upload preserves the directory structure

---

README.md
serve.js

feat: allow for the port to be configured

---

src/components/Card.tsx
src/components/Map.tsx
src/components/SwarmButton.tsx
src/pages/info/index.tsx
src/theme.tsx

This should be merged after #378 because that PR alters styles a lot. I did not spend time sorting out the typography as that is something that is heavily altered by that PR.

feat: info page redesign

---

package-lock.json
package.json
src/App.tsx
src/pages/account/wallet/AccountWallet.tsx
src/pages/gift-code/index.tsx
src/pages/rpc/index.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/GiftCardTopUpIndex.tsx
src/pages/top-up/Swap.tsx
src/pages/top-up/index.tsx
src/providers/Bee.tsx
src/providers/TopUp.tsx
src/utils/identity.ts
src/utils/rpc.ts
src/utils/wallet.ts

fix: all wallet flows to use ethers

---

src/App.tsx
src/utils/sentry.ts

This adds support for tunneling endpoint.
Related to https://github.com/ethersphere/bee-desktop/pull/112

feat: sentry proxy

---

src/components/SideBar.tsx
src/components/SwarmSelect.tsx
src/pages/files/Upload.tsx
src/pages/files/UploadActionBar.tsx
src/pages/stamps/PostageStampSelector.tsx

- Fixes "Files" in sidebar, so that it is active when accessing subpages
- Stamp selector has a placeholder "Please select a postage stamp"
- User is locked on "purchase postage stamp" page when uploading but has no stamp yet

feat: improve stamp selector

---

src/components/Map.tsx
src/pages/info/index.tsx

fix: change color of pins and show population instead of depth

---

package-lock.json
package.json
src/components/SideBar.tsx

feat: add updated sidebar icons

---

src/components/Map.tsx
src/pages/info/index.tsx

fix: info page card and map error states

---

src/App.tsx
src/components/Feedback.tsx
src/hooks/apiHooks.tsx
src/layout/Dashboard.tsx
src/pages/info/index.tsx
src/utils/desktop.ts

feat: version check and info

---

src/pages/restart/LightModeRestart.tsx
src/providers/Bee.tsx

fix: bee data auto-refresh

---

src/pages/account/feeds/AccountFeeds.tsx
src/pages/files/UploadLander.tsx
src/pages/info/NodeInfoCard.tsx
src/pages/info/index.tsx

fix: add troubleshooting checks

---

src/components/SideBar.tsx
src/pages/account/wallet/AccountWallet.tsx
src/pages/files/Download.tsx

Account page only shows wallet setup
File page only shows download

feat(ultra-light): block features that are not available in this mode

---

src/pages/files/UploadActionBar.tsx
src/pages/rpc/index.tsx
src/pages/stamps/PostageStampCreation.tsx

feat: add postage stamp guide

---

src/pages/rpc/Confirmation.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/Swap.tsx
src/routes.tsx

fix: users can now upgrade to light node if they have enough funds

---

src/providers/Bee.tsx

You can test it using `nc -k -l 1635` and `nc -k -l 1633`

fix: status checks have timeout

---

src/components/CashoutModal.tsx
src/components/WithdrawDepositModal.tsx
src/pages/files/Download.tsx
src/pages/files/Upload.tsx
src/pages/gift-code/index.tsx
src/pages/stamps/PostageStampCreation.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/GiftCardTopUpIndex.tsx
src/pages/top-up/Swap.tsx
src/pages/top-up/index.tsx

Resolves #473
unfortunately, there is no hook that could be used in the `notistack`

feat: log errors to console when showing error notification

---

src/components/SideBar.tsx
src/config.ts
src/hooks/apiHooks.test.ts
src/hooks/apiHooks.tsx
src/layout/Dashboard.tsx
src/pages/info/index.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/Swap.tsx
src/pages/top-up/index.tsx

feat: check whether the app runs within bee-desktop is now an environment variable

---

src/pages/info/index.tsx
src/providers/Bee.tsx
src/utils/chain.ts

feat: add wallet endpoint and display blockchain name

---

src/layout/Dashboard.tsx

feat: reintroduce new bee version notification

---

src/App.tsx
src/components/SideBar.tsx
src/hooks/apiHooks.test.ts
src/hooks/apiHooks.tsx
src/layout/Dashboard.tsx
src/pages/account/wallet/AccountWallet.tsx
src/pages/info/index.tsx
src/pages/settings/index.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/Swap.tsx
src/pages/top-up/index.tsx
src/providers/Settings.tsx
src/routes.tsx

feat: pass isBeeDesktop as Bee Dashboard component property

---

src/layout/Dashboard.tsx

fix: new bee version notification is only shown if user bee version is detected

---

src/App.tsx
src/pages/account/wallet/AccountWallet.tsx
src/pages/gift-code/index.tsx
src/pages/info/index.tsx
src/pages/top-up/Balance.tsx
src/pages/top-up/GiftCardFund.tsx
src/pages/top-up/Swap.tsx
src/pages/top-up/index.tsx
src/providers/Bee.tsx
src/providers/WalletBalance.tsx

feat: add loading state to wallet balance

---

src/App.tsx
src/components/ErrorBoundary.tsx
src/layout/Dashboard.tsx

Closes #524 
Using `refactor/removal-env-variables` branch as a base only for better readability.

feat: error reporting callback

---

src/pages/stamps/PostageStampCreation.tsx
src/pages/stamps/PostageStampSelector.tsx

Fixed issues:
#606 Entering * into amount
#630 Stamp Labels

fix: add missing stamp labels and fix inputs

---

src/pages/stamps/PostageStampAdvancedCreation.tsx
src/utils/index.ts

Issue: https://github.com/ethersphere/bee-dashboard/issues/636
Solution:

feat: display effective capacity

---

src/components/SideBar.tsx

feat: add redeem shortcut to sidebar

---

src/containers/DepositModal.tsx
src/containers/WithdrawModal.tsx

fix: clarify withdraw and deposit message

---

.github/workflows/check.yaml
package-lock.json
package.json
src/components/SideBar.tsx
src/pages/fdp/FdpLogin.tsx
src/pages/fdp/FdpPod.tsx
src/pages/fdp/FdpPods.tsx
src/pages/fdp/Horizontal.tsx
src/pages/fdp/Vertical.tsx
src/pages/fdp/index.tsx
src/react-fs/CafeReactFs.tsx
src/react-fs/CafeReactFsCreate.tsx
src/react-fs/CafeReactFsDelete.tsx
src/react-fs/CafeReactFsDirectory.tsx
src/react-fs/CafeReactFsFile.tsx
src/react-fs/CafeReactFsItem.tsx
src/react-fs/CafeReactFsLoading.tsx
src/react-fs/CafeReactFsName.tsx
src/react-fs/CafeReactFsPath.tsx
src/react-fs/CafeReactFsSync.tsx
src/react-fs/CafeReactFsUpload.tsx
src/react-fs/CafeReactType.ts
src/react-fs/Utility.ts
src/routes.tsx

This PR adds a new FDP tab to the sidebar, should be self-contained under `src/pages/fdp`.
`fdp` requires a custom file browser, which is under path `src/react-fs`.
The integration between existing code and new code takes place in `SideBar.tsx` and `routes.tsx`.

feat: add experimental fdp
